"""Data generator class for generating data for testing purposes."""
from __future__ import division, print_function
import random
import string
import time


class OPALDataGenerator(object):
    """Generate data as per OPAL formats for testing purposes.

    Args:
        num_antennas (int): Total number of antennas available.
        num_antennas_per_user (int): Total number of different antennas a user
            can connect to.
        num_records_per_user (int): Number of records generated by each user in
            a day.

    """

    def __init__(
            self, num_antennas, num_antennas_per_user, num_records_per_user):
        self.num_antennas = num_antennas
        self.num_antennas_per_user = num_antennas_per_user
        self.num_records_per_user = num_records_per_user
        self.__interactions = ["call", "text", "text", "text"]
        self.__directions = ["in", "out"]

    def generate_data(self):
        """Generate data for a single user."""
        antennas = [str(random.randint(0, self.num_antennas - 1))
                    for i in range(self.num_antennas_per_user)]
        users = [random.choice(string.ascii_letters) + random.choice(
            string.ascii_letters) for j in range(20)]
        lines = []
        date_props = [random.random() for i in range(
            self.num_records_per_user)]
        date_props.sort()
        for k in range(self.num_records_per_user):
            lines.append(self.__generate_single_line(
                antennas, users, date_props[k]))
        return '\n'.join(lines) + '\n'

    def __generate_single_line(self, antennas, users, date_prop):
        """Generate a single call data record."""
        interaction = random.choice(self.__interactions)
        direction = random.choice(self.__directions)
        user = users[random.randint(0, 19)]
        date = self.__random_date(
            "2016-01-01 00:00:01", "2016-12-31 23:59:59", date_prop)
        receiver_antenna = ''
        if interaction == "call":
            receiver_antenna = str(
                random.randint(0, self.num_antennas - 1))
        caller_antenna = antennas[
            random.randint(0, self.num_antennas_per_user - 1)]
        line = ','.join([
            interaction, direction, user, date, receiver_antenna,
            caller_antenna])
        return line

    def __str_time_prop(self, start, end, format, prop):
        """Generate time as proportion between start time and end time."""
        stime = time.mktime(time.strptime(start, format))
        etime = time.mktime(time.strptime(end, format))
        ptime = stime + prop * (etime - stime)
        return time.strftime(format, time.localtime(ptime))

    def __random_date(self, start, end, prop):
        return self.__str_time_prop(start, end, '%Y-%m-%d %H:%M:%S', prop)
